### ISSUE TITLE
Bantu Syarfani Akbar

### ISSUE THREAD

**Issue by muhdavi** [muhdavi/laporan-practice-big-data#39]
Bantu pull requests pertama

**Comment by zulfahmidev** [comment]
Pastikan sudah melakukan perubahan dan sudah melakukan commit. Jangan lupa lakukan push ke github, di github tekan "Open Pull Request" pada contribute.

**Comment by muhdavi** [comment]
Bantuannya langsung diajarkan caranya ya @zulfahmidev . Sampai bisa melakukan pull reqeuest.

**Comment by muhdavi** [comment]
@traviafzah
